import type { SiteContent } from '../types/content'

export const ptBR: SiteContent = {
  navigation: { about: 'Sobre', reviews: 'Avaliações', faq: 'Dúvidas', contact: 'Contato', quote: 'Solicitar orçamento' },
  hero: { eyebrow: 'Especialistas em qualidade do ar interno', title: 'Ar mais limpo. Mais conforto.', highlight: 'Espaços mais saudáveis.', text: 'Cuidados avançados com HVAC, purificação do ar e ventilação, pensados para a realidade da sua casa, empresa ou instalação.', primary: 'Solicitar orçamento grátis', secondary: 'Ligar 508 615 4433', badge: 'Fresh', badgeText: 'Fluxo de ar projetado para viver melhor.', imageAlt: 'Técnico profissional realizando manutenção em equipamento HVAC moderno' },
  trust: ['Residencial', 'Comercial', 'Industrial', 'Qualidade do ar interno', 'Especialistas em HVAC'],
  about: { eyebrow: 'Sobre a Fresh Air Solutions', title: 'Cuidado especializado com cada respiração no seu ambiente.', paragraphs: ['Na Fresh Air Solutions, somos especialistas em melhorar a qualidade do ar interno e otimizar sistemas de ventilação nos setores residencial, comercial e industrial.', 'Com ampla experiência e compromisso constante com a satisfação dos clientes, entregamos serviços adaptados às necessidades de casas, empresas e indústrias.', 'Entre em contato para descobrir como podemos elevar a qualidade do ar no seu espaço.'], imageAlt: 'Profissional de serviços ajudando a melhorar o ambiente interno residencial' },
  stats: [{ value: '10+', label: 'Anos de experiência' }, { value: '1.200+', label: 'Projetos concluídos' }, { value: '980+', label: 'Clientes satisfeitos' }, { value: '20+', label: 'Áreas atendidas' }],
  testimonials: { eyebrow: 'Histórias de clientes', title: 'Um serviço que ajuda pessoas a respirar melhor.', text: 'As avaliações abaixo são demonstrativas e podem ser substituídas por depoimentos verificados.', items: [{ quote: 'A equipe explicou claramente o problema do fluxo de ar e cuidou muito bem da nossa casa. Todos os cômodos estão mais confortáveis.', name: 'Alex M.', meta: 'Cliente residencial · Demonstração' }, { quote: 'Profissionais, pontuais e fáceis de lidar. Gostamos muito das recomendações práticas de manutenção.', name: 'Jordan R.', meta: 'Cliente de manutenção · Demonstração' }, { quote: 'O ar do nosso escritório está mais fresco e todo o processo respeitou nosso horário de funcionamento.', name: 'Taylor S.', meta: 'Cliente comercial · Demonstração' }] },
  reviews: { eyebrow: 'Avaliações dos clientes', title: 'Uma reputação construída ambiente por ambiente.', score: '4,9', label: 'Média demonstrativa', total: 'Com base em 186 avaliações demonstrativas', recommendation: '98% recomendariam nossos serviços' },
  guarantee: { eyebrow: 'Garantia de serviço', title: 'Sua satisfação está no centro do nosso trabalho.', text: 'Buscamos oferecer comunicação clara, atendimento respeitoso e atenção cuidadosa a cada detalhe combinado. Se você tiver alguma dúvida sobre o serviço realizado, nossa equipe estará pronta para analisar com você.', note: 'Os termos finais da garantia devem ser revisados e aprovados antes da publicação.' },
  cta: { eyebrow: 'Seu ambiente mais saudável começa aqui', title: 'Pronto para respirar um ar mais limpo?', text: 'Conte o que você percebeu e vamos encontrar um caminho prático para obter ar mais limpo e mais conforto.', primary: 'Solicitar orçamento', secondary: 'Ligar 508 615 4433' },
  form: { eyebrow: 'Solicite um orçamento', title: 'Conte como podemos melhorar o seu espaço.', text: 'Compartilhe algumas informações e nossa equipe entrará em contato.', name: 'Nome', email: 'E-mail', phone: 'Telefone', service: 'Serviço', property: 'Tipo de imóvel', message: 'Mensagem', contactMethod: 'Forma de contato preferida', phoneOption: 'Telefone', emailOption: 'E-mail', submit: 'Enviar solicitação', select: 'Selecione uma opção', services: ['Purificação do ar', 'Eliminação de odores', 'Limpeza de duto de secadora', 'Manutenção semestral', 'Qualidade do ar interno', 'Manutenção de HVAC', 'Otimização da ventilação', 'Outro'], properties: ['Residencial', 'Comercial', 'Industrial', 'Administração de imóveis'] },
  contact: { eyebrow: 'Contato Fresh Air Solutions', title: 'Vamos conversar sobre o ar no seu espaço.', phone: 'Telefone', website: 'Site', hours: 'Horários', hoursValue: 'Entre em contato para consultar a disponibilidade', area: 'Área de atendimento', areaValue: 'Ligue para confirmar a cobertura regional' },
  faq: { eyebrow: 'Perguntas frequentes', title: 'Respostas claras sobre um ar mais limpo.', items: [{ question: 'Quais serviços a Fresh Air Solutions oferece?', answer: 'Oferecemos qualidade do ar interno, purificação, eliminação de odores, limpeza de dutos de secadora, manutenção de HVAC e otimização da ventilação para imóveis residenciais, comerciais e industriais.' }, { question: 'Com que frequência devo realizar manutenção no HVAC?', answer: 'Muitos imóveis se beneficiam de manutenção duas vezes ao ano, antes das temporadas de maior uso de refrigeração e aquecimento.' }, { question: 'Como saber se o ar interno precisa de atenção?', answer: 'Poeira recorrente, odores, alergias, fluxo de ar irregular, umidade e ambientes abafados são sinais comuns.' }, { question: 'Com que frequência o duto da secadora deve ser limpo?', answer: 'A frequência depende do uso e da configuração do duto. Secagem mais lenta, calor excessivo ou fiapos visíveis indicam a necessidade de inspeção.' }, { question: 'A purificação do ar pode ajudar com alergias?', answer: 'Uma solução adequada de purificação e filtragem pode ajudar a reduzir partículas no ar, como pólen e poeira.' }, { question: 'Vocês atendem imóveis comerciais e industriais?', answer: 'Sim. Nossos serviços podem ser adaptados para residências, empresas e ambientes industriais.' }, { question: 'O que acontece em uma avaliação do ar interno?', answer: 'Conversamos sobre suas preocupações, analisamos os ambientes relevantes e explicamos recomendações práticas.' }, { question: 'Como posso solicitar um orçamento?', answer: 'Preencha o formulário nesta página ou ligue para a Fresh Air Solutions no número 508 615 4433.' }] },
  quickHelp: { title: 'Precisa de ajuda rápida?', text: 'Fale diretamente com a Fresh Air Solutions sobre sua necessidade de HVAC ou qualidade do ar.', button: 'Ligar 508 615 4433' },
  footer: { description: 'Soluções profissionais de HVAC, ventilação e qualidade do ar interno para espaços residenciais, comerciais e industriais.', navigation: 'Navegação', servicesTitle: 'Serviços', contactTitle: 'Contato', privacy: 'Política de privacidade', terms: 'Termos de serviço', rights: 'Todos os direitos reservados.', social: 'Redes sociais' },
}
