import { useLanguage } from '../../hooks/useLanguage'
import { Button } from '../Button/Button'
import { Container } from '../Container/Container'

export function Hero() {
  const { content } = useLanguage()
  const h = content.hero
  return <section id="home" className="relative overflow-hidden bg-[radial-gradient(circle_at_10%_15%,rgba(54,194,229,.22),transparent_26%),linear-gradient(120deg,#fff_0%,#f3fbfc_68%,#edf8e9_100%)] py-16 sm:py-24"><div className="absolute -left-24 bottom-6 size-56 rounded-full border-2 border-brand-cyan/25"/><div className="absolute -right-24 top-10 size-80 rounded-full border-2 border-brand-cyan/25"/><Container className="relative grid items-center gap-12 lg:grid-cols-[1.08fr_.92fr]"><div><span className="mb-5 inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.16em] text-brand-green-dark"><span className="h-0.5 w-7 bg-brand-cyan" />{h.eyebrow}</span><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-.055em] text-brand-ink sm:text-6xl lg:text-7xl">{h.title} <span className="text-brand-green">{h.highlight}</span></h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-slate-600 sm:text-xl">{h.text}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button href="#quote" size="lg">{h.primary}</Button><Button href="tel:+15086154433" variant="outline" size="lg">{h.secondary}</Button></div></div><div className="relative mx-auto w-full max-w-lg"><img className="min-h-[420px] rounded-[120px_22px_120px_22px] object-cover shadow-[0_25px_70px_rgba(18,42,49,.18)] sm:min-h-[570px]" src="https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=1000&q=85" alt={h.imageAlt}/><div className="absolute bottom-7 left-4 max-w-44 rounded-2xl border border-white/70 bg-white/95 p-4 shadow-xl sm:-left-8"><strong className="block text-2xl font-black text-brand-green-dark">{h.badge}</strong><span className="text-sm text-slate-600">{h.badgeText}</span></div></div></Container></section>
}
